title: The Roberson Letters
author: Jos. S. Roberson
url: htp://therobersonletters.com
email: jos@therobersonletters.com
description: > # this means to ignore newlines until "baseurl:"
  From 1877-1878 Joseph S. Roberson wrote letters to friends, family, and one Miss Emily
  Lofland. Follow along for a rare glimpse into a piece of Americana.

#twitter_username: jekyllrb
#github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

permalink: "/:title"

google_analytics: UA-108107812-1

gems:
  - jekyll-seo-tag
